{
    "openapi": "3.0.0",
    "info": {
        "title": "Laravel Trippo - Auth",
        "description": "L5 Swagger OpenApi description",
        "contact": {
            "email": "mralmaahlol@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url": "http://192.168.137.1:5000",
            "description": "Demo API Server"
        },
        {
            "url": "http://localhost:8000",
            "description": "Test Server"
        }
    ],
    "paths": {
        "/api": {},
        "/api/auth/admin/register": {
            "post": {
                "tags": [
                    "Admin"
                ],
                "summary": "Register Admin",
                "description": "",
                "operationId": "RegisterAdmin",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/RegisterAdminRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "admin register successfully"
                                        },
                                        "data": {
                                            "properties": {
                                                "admin": {
                                                    "$ref": "#/components/schemas/AdminResource"
                                                },
                                                "token": {
                                                    "type": "string",
                                                    "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMzcuMTo1MDAwL2FwaS9hdXRoL3VzZXIvcmVnaXN0ZXIiLCJpYXQiOjE2NTM3NTU5NDgsImV4cCI6MTY1Mzc1OTU0OCwibmJmIjoxNjUzNzU1OTQ4LCJqdGkiOiJvc3gzS3BLR3ZDUWZ0dTZwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.tD0FIsUJx33V0J4g4_qSl3cG2JWHstuvy1FkfhmrXiQ"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/admin/login": {
            "post": {
                "tags": [
                    "Admin"
                ],
                "summary": "Login Admin",
                "description": "",
                "operationId": "LoginAdmin",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LoginAdminRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "admin login successfully"
                                        },
                                        "data": {
                                            "properties": {
                                                "admin": {
                                                    "$ref": "#/components/schemas/AdminResource"
                                                },
                                                "token": {
                                                    "type": "string",
                                                    "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMzcuMTo1MDAwL2FwaS9hdXRoL3VzZXIvcmVnaXN0ZXIiLCJpYXQiOjE2NTM3NTU5NDgsImV4cCI6MTY1Mzc1OTU0OCwibmJmIjoxNjUzNzU1OTQ4LCJqdGkiOiJvc3gzS3BLR3ZDUWZ0dTZwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.tD0FIsUJx33V0J4g4_qSl3cG2JWHstuvy1FkfhmrXiQ"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/admin/logout": {
            "post": {
                "tags": [
                    "Admin"
                ],
                "summary": "logout Admin",
                "description": "",
                "operationId": "logoutAdmin",
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "admin logout successfully"
                                        },
                                        "data": {}
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Error: Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerToken": []
                    }
                ]
            }
        },
        "/api/auth/user/register": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Register User",
                "description": "",
                "operationId": "RegisterUser",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/RegisterUserRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "user register successfully"
                                        },
                                        "data": {
                                            "properties": {
                                                "user": {
                                                    "$ref": "#/components/schemas/UserResource"
                                                },
                                                "token": {
                                                    "type": "string",
                                                    "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMzcuMTo1MDAwL2FwaS9hdXRoL3VzZXIvcmVnaXN0ZXIiLCJpYXQiOjE2NTM3NTU5NDgsImV4cCI6MTY1Mzc1OTU0OCwibmJmIjoxNjUzNzU1OTQ4LCJqdGkiOiJvc3gzS3BLR3ZDUWZ0dTZwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.tD0FIsUJx33V0J4g4_qSl3cG2JWHstuvy1FkfhmrXiQ"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/user/login": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Login User",
                "description": "",
                "operationId": "LoginUser",
                "requestBody": {
                    "required": true,
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/LoginUserRequest"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "user login successfully"
                                        },
                                        "data": {
                                            "properties": {
                                                "user": {
                                                    "$ref": "#/components/schemas/UserResource"
                                                },
                                                "token": {
                                                    "type": "string",
                                                    "example": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vMTkyLjE2OC4xMzcuMTo1MDAwL2FwaS9hdXRoL3VzZXIvcmVnaXN0ZXIiLCJpYXQiOjE2NTM3NTU5NDgsImV4cCI6MTY1Mzc1OTU0OCwibmJmIjoxNjUzNzU1OTQ4LCJqdGkiOiJvc3gzS3BLR3ZDUWZ0dTZwIiwic3ViIjoiMSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.tD0FIsUJx33V0J4g4_qSl3cG2JWHstuvy1FkfhmrXiQ"
                                                }
                                            },
                                            "type": "object"
                                        }
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/api/auth/user/logout": {
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "logout User",
                "description": "",
                "operationId": "logoutUser",
                "responses": {
                    "200": {
                        "description": "Successful operation",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "properties": {
                                        "success": {
                                            "type": "boolean",
                                            "example": "true"
                                        },
                                        "message": {
                                            "type": "string",
                                            "example": "user logout successfully"
                                        },
                                        "data": {}
                                    },
                                    "type": "object"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Error: Unauthorized"
                    }
                },
                "security": [
                    {
                        "bearerToken": []
                    }
                ]
            }
        }
    },
    "components": {
        "schemas": {
            "LoginAdminRequest": {
                "title": "LoginAdminRequest",
                "description": "LoginAdminRequest body data",
                "required": [
                    "username",
                    "password"
                ],
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "username": "admin",
                    "password": "12345678"
                }
            },
            "LoginUserRequest": {
                "title": "LoginUserRequest",
                "description": "LoginUserRequest body data",
                "required": [
                    "username",
                    "password"
                ],
                "properties": {
                    "username": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "username": "mohamad_ra",
                    "password": "12345678"
                }
            },
            "RegisterAdminRequest": {
                "title": "RegisterAdminRequest",
                "description": "RegisterAdminRequest body data",
                "required": [
                    "name",
                    "username",
                    "email",
                    "password",
                    "comfirmation_password"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "comfirmation_password": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "name": "Mohamad Rasoul",
                    "username": "admin",
                    "email": "mralmaahlol@gmail.com",
                    "password": "12345678",
                    "password_confirmation": "12345678"
                }
            },
            "RegisterUserRequest": {
                "title": "RegisterUserRequest",
                "description": "RegisterUserRequest body data",
                "required": [
                    "first_name",
                    "last_name",
                    "username",
                    "email",
                    "password",
                    "comfirmation_password",
                    "about",
                    "gender",
                    "date_of_birthday",
                    "phone_number",
                    "latitude",
                    "longitude"
                ],
                "properties": {
                    "first_name": {
                        "type": "string"
                    },
                    "last_name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "password": {
                        "type": "string"
                    },
                    "comfirmation_password": {
                        "type": "string"
                    },
                    "about": {
                        "type": "string"
                    },
                    "gender": {
                        "type": "string",
                        "enum": [
                            "male",
                            "female"
                        ]
                    },
                    "date_of_birthday": {
                        "type": "string"
                    },
                    "phone_number": {
                        "type": "string"
                    },
                    "latitude": {
                        "type": "string"
                    },
                    "longitude": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "first_name": "Mohamad",
                    "last_name": "Rasoul",
                    "username": "mohamad_ra",
                    "email": "mralmaahlol@gmail.com",
                    "password": "12345678",
                    "password_confirmation": "12345678",
                    "about": "this is my profile",
                    "gender": "male",
                    "date_of_birthday": "15-9-1998",
                    "phone_number": "0958600569",
                    "latitude": "36.1654",
                    "longitude": "37.1545"
                }
            },
            "StoreCityRequest": {
                "title": "StoreCityRequest",
                "description": "StoreCityRequest body data",
                "required": [
                    "name",
                    "description",
                    "latitude",
                    "longitude"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "latitude": {
                        "type": "string"
                    },
                    "longitude": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "name": "Aleppo",
                    "description": "Aleppo is a city in Syria, which serves as the capital of the Aleppo Governorate, the most populous Syrian governorate with an official population of 4.6 million in 2010. Aleppo is one of the oldest continuously inhabited cities in the world; it may have been inhabited since the sixth millennium BC",
                    "latitude": "36.2021",
                    "longitude": "37.1343"
                }
            },
            "AdminResource": {
                "title": "AdminResource",
                "description": "AdminResource body data",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "id": "1",
                    "name": "Mohamad",
                    "username": "mohamad_ra",
                    "email": "mralmaahlol@gmail.com"
                }
            },
            "UserResource": {
                "title": "UserResource",
                "description": "UserResource body data",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "first_name": {
                        "type": "string"
                    },
                    "last_name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "email": {
                        "type": "string"
                    },
                    "about": {
                        "type": "string"
                    },
                    "gender": {
                        "type": "string"
                    },
                    "date_of_birthday": {
                        "type": "string"
                    },
                    "phone_number": {
                        "type": "string"
                    },
                    "latitude": {
                        "type": "string"
                    },
                    "longitude": {
                        "type": "string"
                    }
                },
                "type": "object",
                "example": {
                    "id": "1",
                    "first_name": "Mohamad",
                    "last_name": "Rasoul",
                    "username": "mohamad_ra",
                    "email": "mralmaahlol@gmail.com",
                    "about": "this is my profile",
                    "gender": "male",
                    "date_of_birthday": "1998-09-15T00:00:00.000000Z",
                    "phone_number": "0958600569",
                    "latitude": "36.1654",
                    "longitude": "37.1545"
                }
            }
        },
        "securitySchemes": {
            "bearerToken": {
                "type": "http",
                "description": "Enter token in format (Bearer <token>)",
                "name": "Authorization",
                "in": "header",
                "scheme": "bearer",
                "bearerFormat": "JWT"
            }
        }
    },
    "tags": [
        {
            "name": "User",
            "description": "API Endpoints of City"
        },
        {
            "name": "Admin",
            "description": "API Endpoints of City"
        }
    ]
}